//Projemizin ana bölgesi. Tüm componentlerin çağırıldığı yer.
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Feed from './components/Feed'
import Sidebar from './components/Sidebar'
import Widgets from './components/Widgets'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black min-h-screen flex max-w-[1500px] mx-auto'>
        {/* Üçe böldüğümüz arayüzümüzün her componentini topladığımız bölge */}
        <Sidebar/>
        <Feed/>
        <Widgets/>
      </main>
    </div>
  )
}

